# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tag"
  pageRef = "tags"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/teeramaet"
  weight = 30