# config/_default/menus.toml

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/teeramaet"
  weight = 30